// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID         int64
	Project    string
	Spider     string
	Job        string
	Status     string
	Deleted    bool
	CreateTime time.Time
	UpdateTime time.Time
	Pages      sql.NullInt64
	Items      sql.NullInt64
	Pid        sql.NullInt64
	Start      sql.NullTime
	Runtime    sql.NullString
	Finish     sql.NullTime
	HrefLog    sql.NullString
	HrefItems  sql.NullString
	Node       string
	TaskID     interface{}
	Error      sql.NullString
	StartedBy  interface{}
	StoppedBy  interface{}
}

type ScrapydNode struct {
	ID       int64
	Nodename string
	Url      string
	Username sql.NullString
	Password []byte
}

type Setting struct {
	DefaultProjectPath      sql.NullString
	DefaultProjectName      sql.NullString
	PersistedSpiderSettings sql.NullString
}

type Task struct {
	ID                uuid.UUID
	Name              sql.NullString
	CreateTime        time.Time
	UpdateTime        time.Time
	Project           string
	Spider            string
	Jobid             string
	SettingsArguments string
	SelectedNodes     string
	CronString        string
	Paused            bool
	CreatedBy         interface{}
	ModifiedBy        interface{}
}

type User struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	Username           string
	HashedPassword     string
	HasAdminPrivileges bool
}
